const mongoose=require("mongoose");

const problemSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    difficulty:{
        type:String,
        enum:["Easy","Medium","Hard"],
        required:true,
    },
    tags:{
        type:[String],
        enum:["strings",
                "arrays",
                "linked-list",
                "stacks",
                "queues",
                "hash-maps",
                "sorting",
                "searching",
                "binary-search",
                "graphs",
                "trees",
                "dynamic-programming",
                "backtracking",
                "greedy",
                "heap",
                "bit-manipulation",
                "mathematical",
                "two-pointers",
                "sliding-window",
                "recursion",
                "design",
                "math",
                "prefix-sum",
                "other"],
        required:true,
    },
    visibleTestCases:[
       {
        input:{
            type:String,
            required:true,
        },
        output:{
            type:String,
            required:true,
        },
        explanation:{
            type:String,
            required:true,

        }
       }
    ],
    hiddenTestCases:[
       {
        input:{
            type:String,
            required:true,
        },
        output:{
            type:String,
            required:true,
        },
       }
    ],
    startCode:[{
        language:{
            type:String,
            required:true,
        },
        initialCode:{
            type:String,
            required:true,
        }
    }],
    problemCreator:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true,


    },
     refrenceSolution:[{
        language:{
            type:String,
            required:true,
        },
        completeCode:{
            type:String,
            required:true,
        }
    }]



})
module.exports=mongoose.model("Problem",problemSchema);